### ISSUE TITLE
Custom URLs for OpenAI-Based URL Not Functioning After Version 2.3.1

### ISSUE THREAD

**Issue by PandaNocturne** [longy2k/obsidian-bmo-chatbot#101]
Thank you for the new features in the latest version! However, I noticed that after version 2.3.1, the custom URLs for OpenAI's OpenAI-Based URL are no longer functioning.

![image](https://github.com/user-attachments/assets/e92949c2-b458-47eb-9750-0d9e064b05c8)

Since I'm not using OpenAI's official URL, I need to make some modifications to this URL. It worked well in previous versions, but starting with version 2.3.1, it seems to be malfunctioning. As a result, I have to manually update the link in the main.js file for it to work. I would greatly appreciate it if you could fix this issue. Thank you!

**Comment by QAbot-zh** [comment]
yes，I also meet the problem. How do you fix it?

**Comment by PandaNocturne** [comment]
> yes，I also meet the problem. How do you fix it?是的，我也遇到这个问题了你如何解决它？

I didn't make many modifications because I'm not good at programming. I simply opened the main.js file of the BMO plugin using VSCode and used the shortcut `Ctrl+H` for a global replacement to change `https://api.openai.com` to another link, such as `https://api.openai-sb.com`. After restarting Obsidian, it worked normally. However, this method does not allow for easily defining other links, and I need to modify it again after the plugin is updated. I hope this bug can be fixed in the next update.

**Comment by QAbot-zh** [comment]
嗯确实是某次改动的时候给改回固定 URL 了，估计是测试的时候没注意。我已经针对性提交 pr 了

![image](https://github.com/user-attachments/assets/7f3b394c-7a80-469e-955a-0fa5369a41cb)

**Comment by longy2k** [comment]
v2.3.3

#103 by [QAbot-zh](https://github.com/QAbot-zh)

Thanks!
