### ISSUE TITLE
/Model not working

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#16]
switching models seems to be broken when using /model

**Comment by longy2k** [comment]
Please use the value system for now, such as `/model 1`, `/model 2`, ...

I will fix this sometime this week.

Thanks for letting me know!

**Comment by longy2k** [comment]
Just updated to v1.7.1

Please let me know if that works!

If it still does not work, try re-inserting your api keys.

Thanks

**Comment by twalderman** [comment]
This is working. Thanks
