### ISSUE TITLE
Claude 2.1 

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#17]
The current API will provide access to claude 2.1.  I assume the modification needs to be here:

```ts
// view.ts

export const ANTHROPIC_MODELS = ["claude-instant-1.2", "claude-2.0"];
```

TIA!

**Comment by longy2k** [comment]
Let me know if claude-2.1 is working, thanks

**Comment by twalderman** [comment]
2.1 is working. thanks man. I will send you a tip for your efforts.
