### ISSUE TITLE
Feature request - regenerate / append more easily

### ISSUE THREAD

**Issue by Madd0g** [longy2k/obsidian-bmo-chatbot#18]
Thanks for a nice extension, trying it out with ollama.

1. sometimes ollama fails (UI either shows an empty response or throws an error and keeps playing the loading animation).

Would be nice if there was a regenerate/retry button (+some error handling, I see red error popup that says JSON.parse of the response failed, but it doesn't look like the BMO UI is aware of the error, also ollama is still generating for a long time after the error, so maybe if we handle that JSON.parse error we could "save" the rest of the reply?).

2. I found `/append` and I am a keyboard oriented person, but it's a lot of typing, would be cool if there was a button next to a response to append just that response (or insert where the cursor last was?)

3. Automatic append somehow? I sometimes want to generate-to-insert to the current note and doing it in multiple steps is a little frustrating (I'm using small models, so I'm not having long chats, just prompt then insert to note).

Thanks!

**Comment by longy2k** [comment]
These are great suggestions!

I will refactor the code and add these suggestions in the upcoming weeks as I finish my semester.

Thanks :)

**Comment by longy2k** [comment]
I have added an append button to quickly append any responses and a regenerate button to regenerate the latest response.
I have also added a 'Prompt Select Generate' command which will 'generate-to-insert to the current note.' You can create a prompt, select it, and then run the command to generate a response.

Let me know if v1.8.0 satisfy this feature request.

**Comment by Madd0g** [comment]
Nice! Append button and regenerate work great!

The new palette command is kinda missing feedback, it's just working and the background for a while and then replaces the text, it's not the best experience, but I'm not sure how it should work.

I am experiencing a fairly severe bug with the new version - I cannot turn off "reference active note". the UI shows it as off, but the AI still answers as if it's on.

**Comment by longy2k** [comment]
v1.8.2

I hope this gives a better explanation of how the 'Prompt Select Generate' command should work: https://github.com/longy2k/obsidian-bmo-chatbot/wiki/Prompt---Select---Generate-Command

This might not be the best experience but I added a 'Generating...' notice to show that the 'Prompt Select Generate' command is being executed.

The 'Reference Current Note' should be fixed now. It was storing the previous reference current note with each response. The reference current note now clears before calling for a response.

**Comment by Madd0g** [comment]
nice, looks like the bug with the reference is gone.

append/refresh so far have been the most useful
