### ISSUE TITLE
Ability to edit the context

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#21]
add the ability to edit an entry or response. This would permit the user to alter the context for steering and correction.  I imagine a pencil icon along with the existing copy and delete

**Comment by jmpaz** [comment]
This feature, especially if message history is preserved as in ChatGPT's web client, would propel the project (personally) from useful novelty to must-have utility

**Comment by longy2k** [comment]
v1.8.3

message history is not preserved when regenerating or editing in this version.

**Comment by twalderman** [comment]
@jimpaz - Although I would like to be able to edit the bot message, (VERY MUCH) I have been cutting and pasting the BOT response into my user message preceding the response, editing it and try to steer the conversation.  Alternatively, I save it into a note, edit it and use the obsidian plugin, text generator to continue forward.  In the future, the ability to edit the BOT response would make this a killer creative writing copilot as well as steerable chat/rp client.
