### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#22]
User Story: As a user, I want to save prompts that I commonly use so that I can easily reuse them later with a slash command.

Acceptance Criteria:

1. The system should allow me to save prompts with a descriptive name
2. The system should store my saved prompts for later use
3. I should be able to see a list of my saved prompts
4. I should be able to call up a saved prompt by its name or number using a slash command like /prompt1
5. The chatbot should recognize my saved prompt and respond appropriately when I use the slash command
6. Additional Details:

Support both numbered prompts **/prompt {name}** and named prompts **/prompt {number}
Include confirmation when saving a new prompt**
Allow deleting saved prompts
Store prompts locally so they are available across notes
Allow organizing prompts into categories

**Comment by longy2k** [comment]
Let me know if v1.8.0 satisfy this feature request, thanks

**Comment by twalderman** [comment]
excellent!
