### ISSUE TITLE
/Save is not working

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#24]
since latest release, /save no longer is saving to a file.  /append works as expected as does other  slash commands.

**Comment by longy2k** [comment]
What model were you using?

**Comment by twalderman** [comment]
Claude-2.1

**Comment by twalderman** [comment]
It is working.  However If you allow bmp to name the saved document, it does not confirm the save or open the document.

**Comment by longy2k** [comment]
v1.8.7 should resolve this problem.

After using the `/save` or `/append`, there should be a bot message to let you know that the command has been executed.

Let me know if this works with Anthropic too!
