### ISSUE TITLE
Openrouter.ai support

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#28]
Title: Integrate Open Router API Support in BMO Chat Client

**User Story:** As a user of BMO, the chat client for Obsidian, I want to have the ability to connect to and select from various providers and models supported by openrouter.ai as an API provider, so that I can leverage a diverse range of AI capabilities within my chat experience.

**Acceptance Criteria:**
- Given that I am using BMO, when I access the settings, then I should see an option to connect to the Open Router API.
- Given that I have selected to use the Open Router API, when I am prompted to authenticate, then I should be able to input my credentials and successfully connect to the service.
- Given that I am connected to the Open Router API, when I look for AI providers and models, then I should see a list of all supported options.
- Given that I am viewing the list of providers and models, when I select one, then BMO should use that selection for processing my chat messages.
- Given that I have selected a provider and model, when I send a chat message, then the message should be processed using the chosen AI capabilities.

**Technical Notes:**
- Ensure the integration supports all current providers and models available on openrouter.ai.
- The connection to the Open Router API should be secure and handle authentication tokens appropriately.
- The user interface for selecting providers and models should be intuitive and user-friendly.
- The integration should be designed to easily accommodate updates to the list of providers and models from openrouter.ai.

**Tasks:**
- Research and understand the Open Router API documentation.
- Implement the API connection within BMO's settings.
- Create a user interface for selecting the AI provider and model.
- Handle the authentication process for Open Router API.
- Implement the logic to process chat messages using the selected AI provider and model.
- Test the integration thoroughly to ensure reliability and security.

**Definition of Done:**
- All acceptance criteria are met.
- The feature has been tested across different scenarios and works as expected.
- The code has been reviewed by peers.
- The feature is documented, if necessary.
- The new functionality is merged into the main branch and is deployable.

**Comment by longy2k** [comment]
In v1.8.0, I have updated openai base url to pull the models correctly.

1. Go to https://openrouter.ai and obtain an API Key.
2. Insert the API key in the BMO settings.
3. Update the 'OPENAI BASE URL' to `https://openrouter.ai/api/v1`
4. You should see all the models populate within the model dropdown.

Let me know if that works!

**Comment by longy2k** [comment]
https://github.com/longy2k/obsidian-bmo-chatbot/wiki/How-to-setup-with-Openrouter.ai
