### ISSUE TITLE
Reference doesn't included rendered information

### ISSUE THREAD

**Issue by sherodtaylor** [longy2k/obsidian-bmo-chatbot#29]
The reference only takes file contents regardless of the rendered view. It would be nice to be able to load the rendered view of the file. As we use a lot of plugins like dataviewjs.

```
Note:```\n\n```dataviewjs\nconst average = array => array.reduce((a, b) => a + b) / array.length;\nconst data = await dv.query(...)
```

![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/1483092/866dc295-0255-427a-955a-059942d8cde9)

**Comment by longy2k** [comment]
I have not considered rendered information in the chatbot's response.

I will see if I can make this work, thanks

**Comment by sherodtaylor** [comment]
no worries!

**Comment by longy2k** [comment]
v1.8.9

Sorry this took so long but BMO Chatbot now uses Obsidian Markdown rendering which will enable vault links, images, and other rich text elements (e.g. Obsidian Dataview, iframe, ...).
