### ISSUE TITLE
optimise interface

### ISSUE THREAD

**Issue by peterlionelnewman** [longy2k/obsidian-bmo-chatbot#30]
Thanks for making a tip top app!

I'd love to have the interface updated for better use of the screen space / real-estate.

Specifically, the 'BMO/Chat \n Model: \n Reference' text area takes up lots of room. The text being smaller, and arranged horizontally would be a good start. But removing this all together would be even better, since knowing this information is more of a settings thing? Or even integrate it into the scrolling frame?

<img width="263" alt="Screenshot 2024-01-01 at 12 22 37" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/35971555/2fa72158-899d-4a76-916c-0909a25481ff">

Thanks again,

**Comment by twalderman** [comment]
use this space for possible attributes such as tone and style etc.

**Comment by longy2k** [comment]
v1.8.2

You can now go to `BMO Settings > Appearance > Allow Header` and turn off the display.

Let me know if this works for you :D

**Comment by peterlionelnewman** [comment]
oh wow! thanks @longy2k - looking great
<img width="631" alt="Screenshot 2024-01-16 at 20 45 26" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/35971555/8a88bc0f-065d-4422-a170-63765dede00e">
