### ISSUE TITLE
BOT 'role' is a required property - 'messages.1'  ...

### ISSUE THREAD

**Issue by simjak** [longy2k/obsidian-bmo-chatbot#32]
<img width="342" alt="image" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/20096648/e7faf619-8210-4852-8aee-6781a3b55094">
<img width="803" alt="image" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/20096648/76941e71-dc58-4db5-9c8d-68f9d82e02d0">
<img width="785" alt="image" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/20096648/55218e41-f31f-4de2-a0c9-d7214abdb96c">

**Comment by longy2k** [comment]
Oh, I have not seen this error before.

Let me see if I can reproduce it on my end.

Have you tried clearing the message history (Type `/c` in chat) and trying again?
