### ISSUE TITLE
Feature request - multiple API providers

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#35]
Allow for OAI, Anthropic, OPENROUTER, MISTRAL, to coexist in the config such that models served by each might be selected from a list given that all APIs and keys are valid.

**Comment by longy2k** [comment]
v1.8.7

I will refactor and add more over time.

Thanks :D

**Comment by twalderman** [comment]
great start.  it would be nice to have openai and and open ai alternative (openrouter_ coexist.  I miss my anthropic API access :(
