### ISSUE TITLE
[FR] Support Google Gemini API

### ISSUE THREAD

**Issue by wwjCMP** [longy2k/obsidian-bmo-chatbot#38]
Thank you very much for developing this amazing plugin. Would you update it to support the Google Gemini API ?

**Comment by longy2k** [comment]
I have not looked into the Gemini API but I may add it later on.

At the moment, the best option would probably be checking out [openrouter.ai](https://openrouter.ai/) since they support the Gemini models.

https://github.com/longy2k/obsidian-bmo-chatbot/wiki/How-to-setup-with-Openrouter.ai

**Comment by longy2k** [comment]
v1.8.7
