### ISSUE TITLE
chat return undefined

### ISSUE THREAD

**Issue by Cikaros** [longy2k/obsidian-bmo-chatbot#39]
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/5b3637fb-783e-4455-94ca-66612458b5e4)

**Comment by longy2k** [comment]
What model are you using?

If this is a local LLM, are you using Ollama, LM Studio, or something else?

**Comment by Cikaros** [comment]
I have tried llama.cpp and Ollama
This exists with llama.cpp
Models: openchat-3.5-1210.Q4_K_M.gguf

**Comment by longy2k** [comment]
I have found the issue via the prompt function.

Please create a new issue if this occurs again, thanks!
