### ISSUE TITLE
Feature request: Ability to edit the assistant response

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#41]
As a user, I want the ability to edit the Assistant's response so that I can edit and steer the conversation. 

Provide an icon to edit, similar to the user prompt icon
Provide a method to save the edit
Given that the assistant response has been edited, future responses will use the edits as the context. 

Use case: As a writing tool or brainstorming tool, it is essential to steer the chat conversation or edit elements to comply with the User's vision.

**Comment by longy2k** [comment]
v1.8.7

I hope this works for you!

**Comment by twalderman** [comment]
Game changer!  Great job!
