### ISSUE TITLE
Possible Bug - Prompt Generation does not work openrouter

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#48]
I only get the generation complete dialog and no content generated when using this feature.  Works with ollama with MOST of the models I tried.  Some that are tuned in the modelfile with a custom SYSTEM dont respond. -- I recommend a small model like Mistral for a quick response.  

Verified that it works with Openai GPT4

**Comment by longy2k** [comment]
Let me know if v1.8.7 resolve the prompt generation for OpenRouter.

I will continue to refactor the models in the upcoming weeks.

**Comment by twalderman** [comment]
Yes works as expected.  TYVM
