### ISSUE TITLE
Input box text is unreadable with a bright accent color

### ISSUE THREAD

**Issue by Stakker** [longy2k/obsidian-bmo-chatbot#54]
See image :-)

<img width="339" alt="Screenshot 2024-02-21 at 09 48 07" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/8972595/b80641e4-9672-4263-9946-78c0e6add652">

Elsewhere in Obsidian, all the text on the accent color background (like buttons) is black. That would be one possibility, but I also think the accent color is not the right choice for the input box, because it's used for buttons and similar UI elements.

How about the input box would simply be the same color as the background of your text? I think this would be the most logical and also nicest looking option :-) (Maybe you could choose to use the accent color for the text to make it stand out from "regular text".)

Otherwise this looks like a cool plugin, but it's just unusable for me now :-)
(I'm currently using Copilot, but I don't like its default visual settings that can't be changed.)

**Comment by longy2k** [comment]
v1.8.8

I added `Chatbox Background Color` and `Chatbox Border Color` colorpicker.

Please let me know if adjusting the chatbox appearance will make it more readable.

Thanks

**Comment by Stakker** [comment]
Oh yeah, much better! Now I can actually use it :-)

A minor cosmetic thing is that the "Start typing…" text is now full bright white on a black background. (There is no #FFFFFF in the default or Minimal theme, they use grays.) I would personally prefer it to be dark gray so it would look more like a subtle hint and not stand out so bright. Of course how it looks also depends on your background color setting, and it's a minor niggle anyway :-)

Thanks for the quick fix, I appreciate it! 🙏

**Comment by longy2k** [comment]
v1.9.0 now has more options to customize the chatbot interface.

---

### If you have <v1.9.0, please perform the following instructions:

1. Go to Community Settings and click on the folder's icon:

    <img width="775" alt="Screenshot 2024-03-10 at 9 28 38 PM" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/40724177/62882d8d-77d9-4a46-88fc-4e6a9b1215fc">

2. Close Obsidian completely.
    
3. Find the `bmo-chatbot` folder and delete `data.json`.

4. Restart Obsidian.

**Comment by Stakker** [comment]
Love it, thank you! 🙏
