### ISSUE TITLE
Feature Request - Profiles

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#56]
As a User I would like to save all my BMO settings in Profiles, so I can load presets to switch functionality and settings. 

1) Given that I save a Profile, it is added to the list of valid profiles, so I can select it later as a preset.
2) Given that I make changes to a profile, I can update the saved Profile, so that I can use those settings later.
3) Given that I have an ollama model profile, when I switch profiles, the ollama specific information is changed 
4) Given that a profile has API settings, those settings will be saved in a profile.
5) Given that I change a profile, models will change as well.

**Comment by longy2k** [comment]
Yeah, I plan on implementing presets/profiles soon!

**Comment by twalderman** [comment]
![Intelligence Profile mgmt](https://github.com/longy2k/obsidian-bmo-chatbot/assets/78627063/9617659f-6dd7-4760-a55c-0abdec7c4a7c)

Consider this method for Managing, the loading of presets (assistants) and context (conversations)

**Comment by longy2k** [comment]
v.1.90

## Breaking Changes

### If you have <v1.9.0, please perform the following instructions:

1. Go to Community Settings and click on the folder's icon:

    <img width="775" alt="Screenshot 2024-03-10 at 9 28 38 PM" src="https://github.com/longy2k/obsidian-bmo-chatbot/assets/40724177/62882d8d-77d9-4a46-88fc-4e6a9b1215fc">

2. Close Obsidian completely.
    
3. Find the `bmo-chatbot` folder and delete `data.json`.

4. Restart Obsidian.

**Comment by longy2k** [comment]
When switching profiles/presets, I opted for a `/profile` command.

Type `/p`, `/prof`, `/profiles`, or `/profiles` to list profiles from your specified folder.

Type the command with the corresponding value or name (case insensitive) to switch profiles.

For example:

- `/p 1`
- `/p 2`
- `/p BMO`

**Comment by twalderman** [comment]
This is awesome but there is value in having profiles and separate prompts 
Context should be: 
Profile
Prompt
Ref Doc
Input


This allows for complete versatility.

**Comment by longy2k** [comment]
I can see value in quickly swapping profiles, prompts, and reference docs, depending on the context.

My thought process for this update and future updates is to have everything within your profile system prompt.

For example:

```
You are a helpful assistant.

### Available Prompts
- [[Prompt 1]]
- [[Prompt 2]]
- [[Prompt 3]]

### Available Documents
- [[Document 1]]
- [[Document 2]]
- [[Document 3]]

### Available PDFs & Images
- ...
```

I have not implemented this feature yet but I would like the chatbot LLMs to automatically read the markdown links and provide more relevant context to the user.

Sorry for removing the prompt option so soon. If this direction does not work as intended, I will fall back to the swappable context switching as mentioned.

**Comment by twalderman** [comment]
Consider having both.  Profile specific prompts and the ability to load independent prompts.  More layering is a good thing {system}{prompt01}{prompt02}. My thought would be Profile Prompts would expand a System Prompt for specific purposes. The Core System Prompt would be for 80% and the combined would be for the 20% of use cases where the extension is worth the expense. (Opus is expensive). example, I have a writing assistant for Opus that is 3000 chars, when I want to create personas I load an additional 2048 char prompt and then unload when Im done.  The general Prompts are for loading Persona Prompts themselves so I can interview the Character I create for my writing projects.  The General Prompt can be loaded for tasks (In my use case) for summarization, Template formatting etc. The Ref Doc serves as a collaborative document that I append to and may still be in context when I want it.  You are making great progress in making BMO the most powerful copilot experience for writing within Obsidian. I use "text generator" for simple suggestions and "Smart connections" for research within my entire vault.  BMO is essential for my workflow and with my suggestions in this structure, I can do amazing things.  Thank you so much for your efforts!
