### ISSUE TITLE
RESTAPIURL connection error

### ISSUE THREAD

**Issue by Cikaros** [longy2k/obsidian-bmo-chatbot#58]
llama.cpp is deployed locally, which was previously available but is no longer available
在本地部署了llama.cpp，以前可以使用，但现在不能使用了

![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/f7b7881e-b08d-48a1-bbb4-6167e9f65571)

**Comment by longy2k** [comment]
Yes sorry, I updated the REST API URL for consistency. 

If you are using LM Studio, please insert the REST API URL as `http://localhost:1234/v1`

You can use any URL with `/chat/completions` endpoints.

When you insert `http://localhost:1234/v1`, it will fetch as `http://localhost:1234/v1/chat/completions`.

**Comment by longy2k** [comment]
@Cikaros Have you resolved this?

**Comment by Cikaros** [comment]
yes, but I have a new problem in v2.0.0 . a list of models is not shown
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/68bdc7df-995f-4cbe-b7ee-0091ffc0d912)

**Comment by longy2k** [comment]
The REST API URL Connection is fetching via `/models` and `/chat/completions`. Make sure your url leads to that.

For example, LM Studio default URL is `http//:localhost:1234/v1`.
It will be fetched as
- `http//:localhost:1234/v1/models`
- `http//:localhost:1234/v1/chat/completions`

Open router is slightly different, you need to insert it as `http//:openrouter.ai/api/v1`.

It looks like you're using a custom url, check if it's pulling the models from `http//:localhost:8080/v1/models`?

**Comment by Cikaros** [comment]
@longy2k It is OK
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/0cd4e9df-df1d-4347-9f02-9c443d1c8771)

**Comment by Cikaros** [comment]
@longy2k The following error is reported in the developer tool :
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/7a0ea486-9f29-439f-8ebb-6d0aeebfe12e)

**Comment by longy2k** [comment]
Oh, I see!

Check `BMO Chatbot > Profiles` and ensure that the profile folder path is inserted and the profile is selected. The default path should be `BMO/profiles` and the default profile is "BMO". 

1. Locate the folder in your vault.
2. Try deleting the "BMO" profile completely. This should create a new default profile called "BMO". If a new file does not appear, try restarting Obsidian to see if `BMO/Profile/BMO` exist.
3. Then go back to the BMO Chatbot settings an re-insert your urls.

Let me know if that works.

**Comment by Cikaros** [comment]
@longy2k Sorry, it didn't do anything . The following is the error message :
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/75178a0e-9b92-4374-a7ae-4d8951f0a567)

**Comment by longy2k** [comment]
I just tested the REST API URL Connection with `https://openrouter.ai/api/v1` and `https://api.together.xyz/v1` using their provided API keys and it worked fine for me.

This appears to be an issue on your end.

Your API key does not seem to work. Are you able to run your custom URL without an API key?

**Comment by Cikaros** [comment]
This is an error. I did not fill in OpenRouter key
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/a9fea5a7-e09d-40b8-bde5-e3802a237544)
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/be140bef-dd06-455f-9fbb-51bfedb3875a)
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/c0794d06-01e2-42e3-9e0a-efc06dd19a3c)

**Comment by Cikaros** [comment]
I annotated it and it looks fine, but there are still other errors.
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/46598867/464f2a55-d7b3-41fc-ac20-df51f9325bda)

**Comment by longy2k** [comment]
Oh okay, I do notice that filling in the REST API URL prevent open router to pull its model at times. I will try to work on it this weekend. 

Maybe you can try deleting the plugin and re-installing to see if that works in the meantime?

Thanks

**Comment by twalderman** [comment]
I was getting errors with jan.ai too during an experiment. wouldnt retrieve models.

**Comment by longy2k** [comment]
Sorry for the let response, let me know if v2.1.0 resolve this issue.

Thanks!
