### ISSUE TITLE
Prompt Select Generate System - Not working with Anthropic

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#60]
When Anthropic is set as the provider, the renaming of a document feature doesnt seem to work, OAI no issue.  I didnt try with ollama or other.

**Comment by Propheticus** [comment]
I only got this to work on chat history notes, not on 'normal' notes.

**Comment by longy2k** [comment]
v2.2.0

I'm assuming this is an old issue and have been resolved with the latest update.

Please re-open if the issue is still relevant. Thanks!
