### ISSUE TITLE
Re-enable /prompts

### ISSUE THREAD

**Issue by twalderman** [longy2k/obsidian-bmo-chatbot#64]
Please reimplement PROMPTS.  By layering Prompts {system}{prompt} and then input and/or /{refdoc} you allow the system prompt to be layered.  I have built a library of prompts that add to the function of the System prompt for a specific task and/or helping to make the core system prompt economical and only loading a prompt when a task was required. Profiles are awesome and I understand I can make a myriad of profiles, but this is not ideal.  Please consider this.

**Comment by longy2k** [comment]
Yes, I understand why separating between profiles and prompts is essential.

Will add this back soon!

**Comment by twalderman** [comment]
Move to close.  Thank you very much!
