### ISSUE TITLE
[Functional Error] "/" anywhere in the prompt is causing errors.

### ISSUE THREAD

**Issue by AnshJain-Shwalia** [longy2k/obsidian-bmo-chatbot#70]
For ex-> if given the prompt "tell me about the moons /". the output you would expect would be some paragraphs asking about which moon the AI should tell you about.

However any prompt which contains "/" is throwing errors.

![Screenshot from 2024-04-20 16-52-03](https://github.com/longy2k/obsidian-bmo-chatbot/assets/69765978/4bd0fb2a-9170-4d03-a173-221810183394)

**Comment by longy2k** [comment]
v2.1.0

Sorry for the late response, this should be fixed now.
