### ISSUE TITLE
Feature requests - Reference links

### ISSUE THREAD

**Issue by ArmainAP** [longy2k/obsidian-bmo-chatbot#82]
While BMO is able to reference the current note, I would like it to also be able to follow up a link reference properly. 

For example, "Analyse [[2024-01-08]]" should allow it to reference the content from that day without it being open. 

Alternative, I should be able to reference paragraphs as well: "Analyse ![[2024-01-08#Today I am grateful for]]" 

The above examples are from a personal use case and the notes name represent days for my journal. 

I might look into this myself if nobody else picks it up, but at the moment I don't have an ETA  for when I can start as I am stretched a bit too thin across multiple projects.

**Comment by longy2k** [comment]
Check out v2.1.0 :D

[How to render reference links in BMO Chatbot · longy2k/obsidian-bmo-chatbot Wiki](https://github.com/longy2k/obsidian-bmo-chatbot/wiki/How-to-render-reference-links-in-BMO-Chatbot)
