### ISSUE TITLE
Error: messages for role:user the following must be satisfied

### ISSUE THREAD

**Issue by undiabler** [longy2k/obsidian-bmo-chatbot#84]
Have two obsidian folders. One works fine, the other gives error.
Cant figure out what is the conflict. Tried to disable all installed plugins, no luck.
Please help to identify source of this error:

Error: 'messages.1' : for 'role:user' the following must be satisfied[('messages.1' : property 'images' is unsupported, did you mean 'name'?)]

![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/4733217/a7b4a5bf-3829-4134-ab7b-c075dbccb75e)

**Comment by longy2k** [comment]
What API connection are you using?

**Comment by undiabler** [comment]
Okay, i have updated plugin in previously working obsidian folder and now it stops working also.
I have figured out that I cant use Groq API in openai configuration section anymore.

**Comment by longy2k** [comment]
Try using the Groq API under the REST API Connection?

Use the reload button next to the model dropdown to reload the models.

**Comment by undiabler** [comment]
Can confirm its working under the REST API Connection.
