### ISSUE TITLE
Error: Request failed, status 400

### ISSUE THREAD

**Issue by Kang-geophysics** [longy2k/obsidian-bmo-chatbot#85]
BMO Chatbot
- version: 2.1.0

Thank you for your contribution. I have been satisfied with this plugin; it's very smart and easy to use. However, after updating to the new version, I've encountered a new error: "Error: Request failed, status 400." What happened? I thought I should check the console. The console indicated ~ .... Hmm, I'm at a loss. Could you assist me? Why is this error occurring?

![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/56065588/60645a7a-6f70-477a-a296-97e634a6a76f)
![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/56065588/b214aed2-1cc5-4324-973e-d81e8f96e37d)

**Comment by longy2k** [comment]
I am assuming you are using an Ollama connection?

Please update to v2.1.1 and follow these instructions: https://github.com/longy2k/obsidian-bmo-chatbot/wiki/How-to-setup-with-Ollama

V2.1.0 was not able to pull models from the Ollama connection besides from the default value of `http://localhost:11434`.

**Comment by Kang-geophysics** [comment]
Thank you for the recommendation. I installed Lamma and attempted to run `OLLAMA_ORIGINS=* OLLAMA_HOST=127.0.0.1:11435 ollama serve` in PowerShell, but it didn't work. I believe I need to add environment variables. Subsequently, I realized that I had previously used this with the "Groq" API. After enabling the Stream in the options, it now works well. Thank you.
