### ISSUE TITLE
Anthropic latest LLM doesn't appear

### ISSUE THREAD

**Issue by JoelShepard** [longy2k/obsidian-bmo-chatbot#91]
I tried to use my anthropic account to test Claude 3.5 Sonnet but it doesn't appear on BMO. Any ideas on how to solve ?

**Comment by longy2k** [comment]
I have to manually add Anthropic's models into BMO. I will add the new Claude 3.5 Sonnet soon. Thanks

**Comment by longy2k** [comment]
Check v2.1.2 :)
