### ISSUE TITLE
Failed to install plugin 'BMO Chatbot'

### ISSUE THREAD

**Issue by PKeyes505** [longy2k/obsidian-bmo-chatbot#94]
When installing BMO Chatbot via the Community Plugins I get "Failed to install plugin 'BMO Chatbot'" after pressing install.

**Comment by andeeisaacs** [comment]
Running into the same issue.

**Comment by longy2k** [comment]
Sorry, should be fixed now.

Check v2.3.1

**Comment by PKeyes505** [comment]
Confirmed working for me.  Thank you for the quick fix.

**Comment by dannysmallbone** [comment]
Working for me, amazing quick fix. Thanks for your rapid work!
