### ISSUE TITLE
BMO Chat Window Gets Triggered After Renaming an Asset

### ISSUE THREAD

**Issue by edlime** [longy2k/obsidian-bmo-chatbot#96]
OS: MacOS Sonoma 14.5
Obsidian Vault is encrypted using Cryptomator

Scenario:
While Obsidian Vault is open

1. Rename a JPG file from the asset folder inside Obsidian Vault using _Finder_ app.
2. After renaming, the window switches from _Finder_ to Obsidian and the cursor is pointed at BMO Chat input text box.

Not a major issue but gets annoying after renaming many files.

**Comment by kiradzS** [comment]
This also happens when deleting files😭

**Comment by edlime** [comment]
Version 2.3.2 fixed the issue.
