### ISSUE TITLE
GPT-4o mini is here

### ISSUE THREAD

**Issue by JoelShepard** [longy2k/obsidian-bmo-chatbot#97]
Hi. I'm here again. This issue is just to inform you that openAI released GPT-4o mini that is more cheaper than GPT-4o standard.
Please also consider to change the fetch method of models, in order to make this process automatic and change-proof. I know that [this plugin](https://github.com/nhaouari/obsidian-textgenerator-plugin.git) has got this feature and it will be amazing to have that feature on this plugin too.

**Comment by longy2k** [comment]
v2.3.2

`gpt-4o-mini` is now available.

And yes, I should fetch all gpt models automatically down the line. This is just a quick fix for now.

Thanks

**Comment by danieltomasz** [comment]
@longy2k  thank for adding `gpt-4o-mini`!
I had one  issue - the "reload" button - I missed it first time, and I was a bit confused why I cannot find the `gpt-4o-mini` on the list, even after the restart of Obsidian(even if I know that the model was just added, people who doesnt check GitHub might miss it - should the list of available models be reloaded with every obsidian restart for example? I can make a new issue)

**Comment by JoelShepard** [comment]
> v2.3.2
> 
> `gpt-4o-mini` is now available.
> 
> And yes, I should fetch all gpt models automatically down the line. This is just a quick fix for now.
> 
> Thanks

Thank you so much. Good job
