### ISSUE TITLE
/profile command doesn't change the profile anymore

### ISSUE THREAD

**Issue by jppaolim** [longy2k/obsidian-bmo-chatbot#98]
Since the update to latest version (as of 19/07) the /profile command doesn't change the profile anymore.
Basically nothing happens except that when asked about current profile (via /profile) the new profile is displayed as current but the name of the bot hasn't changed, and the model hasn't been updated so I know there was no change. 

The dropdown menu in the settings still works.  

I am using obsidian 1.6.7 on MacOS.

**Comment by twalderman** [comment]
I've seen this too. Rebuilding the pane by clicking on the bmo ribbon is a quick fix.

**Comment by jppaolim** [comment]
Looks solved with latest.
