### ISSUE TITLE
Open-webui integration?

### ISSUE THREAD

**Issue by rwjack** [longy2k/obsidian-bmo-chatbot#99]
Hey, any plans on making this addon work with Open-webui?

It kind of makes sense to do so, since most of the people running ollama will likely also be running open-webui, and with open-webui running, from a security standpoint, it makes sense to put it behind a reverse proxy and make it the only available authenticated endpoint, instead of also having the unauthenticated ollama endpoint available.

**Comment by karl0ss** [comment]
I assume you worked this out? but you can do this by using the REST API connection 

add `/ollama/v1` to the end of your public OpenWebUI url and create an API key in OpenWebUI for use, works no issues..

**Comment by rwjack** [comment]
I did not fully, but you certainly nudged me in the right direction, thanks!

**Comment by rwjack** [comment]
https://github.com/acon96/home-llm/issues/208

**Comment by rwjack** [comment]
@karl0ss hey just to confirm,

I need to set the url in both places in settings?

![image](https://github.com/user-attachments/assets/9a56e8e8-02eb-4840-98fd-3b3db29159ca)


![image](https://github.com/user-attachments/assets/6814279c-860f-4fdc-826d-ca28b7a8e3fa)

Because I'm getting this:

![image](https://github.com/user-attachments/assets/4436ebab-fff2-44b8-a180-5007836ccc4e)

**Comment by rwjack** [comment]
Unsure what's the deal, because I'm seeing the available model in settings, even after refreshing:

![image](https://github.com/user-attachments/assets/548ce969-e201-44ea-b46a-16aae350542f)

**Comment by rwjack** [comment]
Hmm, the certs are valid, although signed by an internal CA, trusted by my system. Could it be that Obsidian isn't respecting the system CA store?

**Comment by rwjack** [comment]
Oddly enough, I opened obsidian on my laptop (was trying from Desktop) and it worked. Hopefully it stays that way

Cheers boss 🥂
